name: tutor_platform
description: "모두의 튜터"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  flutter_secure_storage: ^4.2.1
  http: ^1.2.2
  syncfusion_flutter_datepicker: ^26.2.9
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  build_runner: ^2.4.11
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600

  assets:
    - assets/images/
    - assets/images/starting_screen/
    - assets/icons/
    - assets/images/successful_register/