name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - feat/be  # feat/be 브랜치에 푸시할 때만 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'ap-northeast-2'
      ECR_REGISTRY: '975050350378.dkr.ecr.ap-northeast-2.amazonaws.com'
      ECR_REPOSITORY: 'modu/springrepo'
      IMAGE_TAG: 'v1'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY .

      - name: Tag Docker image
        run: |
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
